---
apiVersion: v1
kind: Service
metadata:
  namespace: production
  name: external-sql
spec:
  ports:
  - protocol: TCP
    port: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  namespace: production
  name: external-sql
subsets:
  - addresses:
      - ip: 10.20.30.32
    ports:
      - port: 3306
